# Dependencies
markdown:         kramdown
pygments:     	  pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Aaron Rono
tagline:          'An Android Enthusiast'
description:      'Up next...Story of my life'
url:              http://hyde.getpoole.com
baseurl:          

author:
  name:           'Aaron Rono'
  url:            https://twitter.com/Aroniez

paginate:         5 

# Custom vars
version:          2.1.0

encoding:         utf-8

github:
  repo:           https://github.com/Aroniez/aroniez.github.io
  
